apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.statefulSetName }}
  ports:
    - port: {{ .Values.servicePort}}
      name: {{ .Values.servicePortName }}
  type: {{ .Values.serviceType }}
