apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSetName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.statefulSetName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.statefulSetName }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ .Values.statefulSetName }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Values.containerName }}
          image: {{ .Values.dbimage }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbeInitialDelay }}
            periodSeconds: {{ .Values.readinessProbePeriod }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbeInitialDelay }}
            periodSeconds: {{ .Values.readinessProbePeriod }}
          resources:
            requests:
              cpu: {{ .Values.requestsCpu }}
              memory: {{ .Values.requestsMemory }}
            limits:
              cpu: {{ .Values.limitsCpu }}
              memory: {{ .Values.limitsMemory }}
          volumeMounts:
            - name: {{ .Values.pvcName }}
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.pvcName }}
        namespace: {{ .Release.Namespace }}
      spec:
        accessModes:
          - {{ .Values.pvcAccessMode }}
        resources:
          requests:
            storage: {{ .Values.pvcSize }}